name: Lua syntax check
on: [pull_request, push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y luarocks && sudo luarocks install luacheck
      - run: luacheck Core.lua Options.lua
